"""Add user_id

Revision ID: 9cbf5b3daf10
Revises: df04cf5452f0
Create Date: 2026-07-06 19:55:08.556374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbf5b3daf10'
down_revision: Union[str, Sequence[str], None] = 'df04cf5452f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'user_id')
    # ### end Alembic commands ###
