"""Update AIAnalysis model

Revision ID: e4dabe664c0a
Revises: bedeb0b17a90
Create Date: 2026-07-07 12:16:07.808119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4dabe664c0a'
down_revision: Union[str, Sequence[str], None] = 'bedeb0b17a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis', sa.Column('complaint_id', sa.Integer(), nullable=False))
    op.add_column('ai_analysis', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('ai_analysis', sa.Column('department', sa.String(length=100), nullable=False))
    op.add_column('ai_analysis', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('ai_analysis', sa.Column('suggested_action', sa.Text(), nullable=False))
    op.alter_column('ai_analysis', 'summary',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('ai_analysis', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_unique_constraint(None, 'ai_analysis', ['complaint_id'])
    op.create_foreign_key(None, 'ai_analysis', 'complaints', ['complaint_id'], ['id'])
    op.drop_column('ai_analysis', 'predicted_department')
    op.drop_column('ai_analysis', 'priority_score')
    op.drop_column('ai_analysis', 'predicted_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis', sa.Column('predicted_category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('ai_analysis', sa.Column('priority_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ai_analysis', sa.Column('predicted_department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_analysis', type_='foreignkey')
    op.drop_constraint(None, 'ai_analysis', type_='unique')
    op.alter_column('ai_analysis', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_analysis', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('ai_analysis', 'suggested_action')
    op.drop_column('ai_analysis', 'priority')
    op.drop_column('ai_analysis', 'department')
    op.drop_column('ai_analysis', 'category')
    op.drop_column('ai_analysis', 'complaint_id')
    # ### end Alembic commands ###
