// ── Mock Data for Citizen Dashboard ──────────────────────────────────────────
// Replace with real API calls when backend is ready

import type { DashboardStats, Notification, UpcomingDeadline } from "../types/citizen";
import type { Complaint } from "../types/complaint";
import type { Scheme, SchemeApplication } from "../types/scheme";
import type { ChatConversation, SuggestedQuestion } from "../types/chat";

export const mockStats: DashboardStats = {
  totalComplaints: 12,
  resolvedComplaints: 8,
  pendingComplaints: 4,
  activeApplications: 3,
  bookmarkedSchemes: 7,
  aiChatsCount: 24,
};

export const mockComplaints: Complaint[] = [
  {
    id: "c1",
    ticketNumber: "JM-2024-001",
    title: "Broken streetlight on MG Road",
    description: "The streetlight near MG Road intersection has been non-functional for 3 weeks, causing safety issues at night.",
    category: "electricity",
    status: "in_progress",
    priority: "high",
    department: "Municipal Corporation",
    location: "MG Road, Near Central Park",
    district: "Lucknow",
    state: "Uttar Pradesh",
    attachments: [],
    comments: [
      { id: "cm1", author: "Rahul Kumar", role: "citizen", message: "This is affecting road safety daily.", createdAt: "2024-01-15T10:00:00Z" },
      { id: "cm2", author: "Officer Singh", role: "officer", message: "We have assigned a team. Expected resolution in 3 days.", createdAt: "2024-01-16T14:00:00Z" },
    ],
    timeline: [
      { id: "t1", status: "submitted", message: "Complaint submitted", actor: "Rahul Kumar", timestamp: "2024-01-15T09:00:00Z", isCompleted: true },
      { id: "t2", status: "acknowledged", message: "Received by Municipal Corporation", actor: "System", timestamp: "2024-01-15T11:00:00Z", isCompleted: true },
      { id: "t3", status: "in_progress", message: "Assigned to maintenance team", actor: "Officer Singh", timestamp: "2024-01-16T14:00:00Z", isCompleted: true },
      { id: "t4", status: "resolved", message: "Awaiting resolution", actor: "", timestamp: "", isCompleted: false },
    ],
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-01-16T14:00:00Z",
    assignedTo: "Officer Singh",
    mpName: "Arvind Sharma",
  },
  {
    id: "c2",
    ticketNumber: "JM-2024-002",
    title: "Potholes on NH-28 causing accidents",
    description: "Multiple large potholes on NH-28 near Aliganj flyover have caused two bike accidents this week.",
    category: "roads",
    status: "submitted",
    priority: "urgent",
    department: "PWD",
    location: "NH-28, Aliganj Flyover",
    district: "Lucknow",
    state: "Uttar Pradesh",
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", status: "submitted", message: "Complaint submitted", actor: "Rahul Kumar", timestamp: "2024-01-17T10:00:00Z", isCompleted: true },
    ],
    createdAt: "2024-01-17T10:00:00Z",
    updatedAt: "2024-01-17T10:00:00Z",
  },
  {
    id: "c3",
    ticketNumber: "JM-2024-003",
    title: "Water supply disruption in Gomti Nagar",
    description: "Water supply has been erratic for 2 weeks. Residents are facing severe inconvenience.",
    category: "water",
    status: "resolved",
    priority: "high",
    department: "Jal Nigam",
    location: "Gomti Nagar, Sector 8",
    district: "Lucknow",
    state: "Uttar Pradesh",
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", status: "submitted", message: "Complaint submitted", actor: "Rahul Kumar", timestamp: "2024-01-10T09:00:00Z", isCompleted: true },
      { id: "t2", status: "acknowledged", message: "Received", actor: "System", timestamp: "2024-01-10T11:00:00Z", isCompleted: true },
      { id: "t3", status: "in_progress", message: "Pipeline repair initiated", actor: "Officer", timestamp: "2024-01-12T10:00:00Z", isCompleted: true },
      { id: "t4", status: "resolved", message: "Water supply restored", actor: "Jal Nigam", timestamp: "2024-01-14T16:00:00Z", isCompleted: true },
    ],
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-14T16:00:00Z",
    resolvedAt: "2024-01-14T16:00:00Z",
  },
  {
    id: "c4",
    ticketNumber: "JM-2024-004",
    title: "Garbage not collected for 10 days",
    description: "The garbage truck hasn't come to our lane for 10 days. Overflowing bins causing health hazard.",
    category: "sanitation",
    status: "acknowledged",
    priority: "medium",
    department: "Municipal Corporation",
    location: "Rajajipuram, Block C",
    district: "Lucknow",
    state: "Uttar Pradesh",
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", status: "submitted", message: "Complaint submitted", actor: "Rahul Kumar", timestamp: "2024-01-18T08:00:00Z", isCompleted: true },
      { id: "t2", status: "acknowledged", message: "Received and under review", actor: "System", timestamp: "2024-01-18T10:00:00Z", isCompleted: true },
    ],
    createdAt: "2024-01-18T08:00:00Z",
    updatedAt: "2024-01-18T10:00:00Z",
  },
];

export const mockSchemes: Scheme[] = [
  {
    id: "s1",
    title: "Pradhan Mantri Awas Yojana - Gramin",
    shortTitle: "PMAY-G",
    description: "Housing for all scheme providing financial assistance for construction/enhancement of houses to rural poor.",
    category: "housing",
    ministry: "Ministry of Rural Development",
    launchDate: "2016-11-20",
    deadlineDate: "2024-12-31",
    status: "open",
    eligibility: {
      income: 300000,
      category: ["sc", "st", "obc"],
      description: "Rural households without pucca house, annual income below ₹3 lakhs",
    },
    benefits: [{ type: "cash", amount: 120000, description: "₹1.2 lakh for plain areas" }],
    documents: [
      { name: "Aadhaar Card", required: true },
      { name: "Income Certificate", required: true },
      { name: "Caste Certificate", required: false },
      { name: "Bank Passbook", required: true },
    ],
    isBookmarked: true,
    isEligible: true,
    applicantsCount: 2847000,
    successRate: 87,
    tags: ["housing", "rural", "financial assistance"],
  },
  {
    id: "s2",
    title: "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana",
    shortTitle: "AB-PMJAY",
    description: "World's largest health insurance scheme providing coverage up to ₹5 lakh per family per year.",
    category: "health",
    ministry: "Ministry of Health & Family Welfare",
    launchDate: "2018-09-23",
    status: "open",
    eligibility: {
      income: 500000,
      description: "Economically weak households as per SECC 2011 data",
    },
    benefits: [{ type: "insurance", amount: 500000, description: "Cashless treatment at empanelled hospitals" }],
    documents: [
      { name: "Aadhaar Card", required: true },
      { name: "Ration Card", required: true },
    ],
    isBookmarked: false,
    isEligible: true,
    applicantsCount: 55000000,
    successRate: 92,
    tags: ["health", "insurance", "medical"],
  },
  {
    id: "s3",
    title: "PM Kisan Samman Nidhi",
    shortTitle: "PM-KISAN",
    description: "Direct income support of ₹6000 per year to farmer families in three equal installments.",
    category: "agriculture",
    ministry: "Ministry of Agriculture",
    launchDate: "2019-02-01",
    status: "open",
    eligibility: {
      description: "Small and marginal farmer families with cultivable land",
    },
    benefits: [{ type: "cash", amount: 6000, description: "₹6,000 per year in 3 installments" }],
    documents: [
      { name: "Aadhaar Card", required: true },
      { name: "Land Records", required: true },
      { name: "Bank Passbook", required: true },
    ],
    isBookmarked: true,
    isEligible: false,
    applicantsCount: 110000000,
    successRate: 95,
    tags: ["agriculture", "farmers", "income support"],
  },
  {
    id: "s4",
    title: "National Scholarship Portal",
    shortTitle: "NSP",
    description: "One-stop digital platform for students to apply for pre & post matric scholarships.",
    category: "education",
    ministry: "Ministry of Education",
    launchDate: "2015-07-01",
    deadlineDate: "2024-11-30",
    status: "open",
    eligibility: {
      age: { min: 14, max: 25 },
      income: 200000,
      description: "Students from SC/ST/OBC/minority communities",
    },
    benefits: [{ type: "cash", amount: 20000, description: "Varies by scholarship and level" }],
    documents: [
      { name: "Aadhaar Card", required: true },
      { name: "Marksheet", required: true },
      { name: "Income Certificate", required: true },
    ],
    isBookmarked: false,
    isEligible: true,
    applicantsCount: 15000000,
    successRate: 78,
    tags: ["education", "scholarship", "students"],
  },
  {
    id: "s5",
    title: "PM Mudra Yojana",
    shortTitle: "PMMY",
    description: "Provides micro-finance loans to non-corporate, non-farm small/micro enterprises up to ₹10 lakh.",
    category: "finance",
    ministry: "Ministry of Finance",
    launchDate: "2015-04-08",
    status: "open",
    eligibility: {
      description: "Non-farm, non-corporate micro/small enterprises",
    },
    benefits: [{ type: "loan", amount: 1000000, description: "Loans from ₹50,000 to ₹10 lakh under Shishu, Kishore, Tarun" }],
    documents: [
      { name: "Aadhaar Card", required: true },
      { name: "Business Plan", required: true },
      { name: "Bank Statement", required: true },
    ],
    isBookmarked: true,
    isEligible: true,
    applicantsCount: 40000000,
    successRate: 82,
    tags: ["loan", "business", "entrepreneurship"],
  },
  {
    id: "s6",
    title: "Beti Bachao Beti Padhao",
    shortTitle: "BBBP",
    description: "Scheme for welfare of girl child and to address declining child sex ratio.",
    category: "women",
    ministry: "Ministry of Women & Child Development",
    launchDate: "2015-01-22",
    status: "open",
    eligibility: {
      gender: "female",
      age: { max: 18 },
      description: "Girl children below 18 years",
    },
    benefits: [{ type: "kind", description: "Educational support, awareness campaigns, healthcare" }],
    documents: [
      { name: "Birth Certificate", required: true },
      { name: "Aadhaar Card", required: false },
    ],
    isBookmarked: false,
    isEligible: false,
    tags: ["women", "girl child", "education"],
  },
];

export const mockApplications: SchemeApplication[] = [
  {
    id: "a1",
    schemeId: "s1",
    schemeName: "PMAY-G",
    schemeCategory: "housing",
    status: "under_review",
    appliedAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    referenceNumber: "PMAY-2024-LKO-00123",
    expectedAmount: 120000,
    remarks: "Documents verified, pending field verification",
  },
  {
    id: "a2",
    schemeId: "s2",
    schemeName: "AB-PMJAY",
    schemeCategory: "health",
    status: "approved",
    appliedAt: "2023-12-05T10:00:00Z",
    updatedAt: "2023-12-20T10:00:00Z",
    referenceNumber: "PMJAY-2023-UP-78901",
    remarks: "Approved. Health card will be delivered within 7 days.",
  },
  {
    id: "a3",
    schemeId: "s5",
    schemeName: "PM Mudra Yojana",
    schemeCategory: "finance",
    status: "submitted",
    appliedAt: "2024-01-18T10:00:00Z",
    updatedAt: "2024-01-18T10:00:00Z",
    referenceNumber: "PMMY-2024-00456",
    expectedAmount: 500000,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "complaint",
    title: "Complaint Updated",
    message: "Your complaint JM-2024-001 has been assigned to a maintenance officer.",
    isRead: false,
    createdAt: "2024-01-16T14:00:00Z",
    href: "/citizen/complaints/c1",
  },
  {
    id: "n2",
    type: "application",
    title: "Application Under Review",
    message: "Your PMAY-G application is being reviewed. Expected response in 7 working days.",
    isRead: false,
    createdAt: "2024-01-15T10:00:00Z",
    href: "/citizen/applications",
  },
  {
    id: "n3",
    type: "scheme",
    title: "New Scheme Available",
    message: "You may be eligible for PM Vishwakarma Yojana. Check your eligibility now.",
    isRead: true,
    createdAt: "2024-01-14T09:00:00Z",
    href: "/citizen/schemes",
  },
  {
    id: "n4",
    type: "complaint",
    title: "Complaint Resolved",
    message: "Your complaint JM-2024-003 about water supply has been resolved.",
    isRead: true,
    createdAt: "2024-01-14T16:00:00Z",
    href: "/citizen/complaints/c3",
  },
  {
    id: "n5",
    type: "system",
    title: "Profile Incomplete",
    message: "Complete your profile to get better scheme recommendations.",
    isRead: true,
    createdAt: "2024-01-12T10:00:00Z",
    href: "/citizen/profile/edit",
  },
];

export const mockUpcomingDeadlines: UpcomingDeadline[] = [
  {
    id: "d1",
    title: "NSP Scholarship Application",
    type: "scheme",
    deadline: "2024-11-30",
    daysLeft: 15,
    schemeId: "s4",
  },
  {
    id: "d2",
    title: "PMAY-G Application Deadline",
    type: "scheme",
    deadline: "2024-12-31",
    daysLeft: 46,
    schemeId: "s1",
  },
];

export const mockConversations: ChatConversation[] = [
  {
    id: "conv1",
    title: "Ayushman Bharat Eligibility",
    preview: "Am I eligible for AB-PMJAY health scheme?",
    lastMessageAt: "2024-01-18T15:30:00Z",
    messageCount: 8,
    isActive: true,
  },
  {
    id: "conv2",
    title: "PMAY Housing Scheme",
    preview: "What documents do I need for PMAY?",
    lastMessageAt: "2024-01-17T11:00:00Z",
    messageCount: 5,
  },
  {
    id: "conv3",
    title: "Grievance Complaint Status",
    preview: "How to check my complaint status?",
    lastMessageAt: "2024-01-15T09:00:00Z",
    messageCount: 3,
  },
];

export const mockSuggestedQuestions: SuggestedQuestion[] = [
  { id: "q1", text: "What government schemes am I eligible for?", category: "schemes" },
  { id: "q2", text: "How do I file a grievance complaint?", category: "complaints" },
  { id: "q3", text: "What is the status of my PMAY application?", category: "applications" },
  { id: "q4", text: "How to apply for Ayushman Bharat health card?", category: "health" },
  { id: "q5", text: "Documents needed for PM Kisan Yojana?", category: "agriculture" },
  { id: "q6", text: "How to connect with my local MP?", category: "mp" },
];
